### ISSUE TITLE
Check out eGenix PyRun

### ISSUE THREAD

**Issue by probonopd** [niess/linuxdeploy-plugin-python#17]
What do you think about this?

>  eGenix PyRun™ is our open source, one file, no installation version of Python, making the distribution of a Python interpreter to run Python based scripts and applications to Unix based systems simple and efficient.
> 
> eGenix PyRun's executable only needs 11MB for Python 2 and 13MB for Python 3, but still supports most Python applications and scripts - and it can be compressed to just 3-4MB using upx, if needed. 
>
>(...)
>
> Easy Installation: Simply drop the executable into a directory and start using it. No installers, no packagers and only a minimal set of dependencies needs to be provided.
Fully Relocatable: eGenix PyRun uses relative search paths, so you can easily move the installation around.
> 
> Compatible with setuptools, easy_install, pip: Great care was taken to make sure that PyRun can be used with setuptools et al. Please note that these tools are not designed to be relocatable.

https://www.egenix.com/products/python/PyRun/

I was able to bundle a PyQt5 app as an AppImage using it in no time:
https://github.com/esa/gr-opssat/pull/5/files#diff-354f30a63fb0907d4ad57269548329e3

**Comment by niess** [comment]
Hello @probonopd . This looks interesting indeed. I wanted to test it, but unfortunately it doesn't seem to work on my side. Running the install script (on Debian 9) I get:

```
Downloading eGenix PyRun ...
Installing eGenix PyRun ...
Installing latest setuptools from PyPI ...
Found latest version 45.0.0
unzip -o setuptools-45.0.0.zip >> /dev/null 2>&1
Failed to install setuptools
```
In principle we could do similar things using the Python AppImages produced by this repo. E.g. extract an image, pip install some extra modules and re-package it, as discussed in [this issue](https://github.com/niess/linuxdeploy-plugin-python/issues/8#issuecomment-549781136). But its a bit hacky for now.

**Comment by niess** [comment]
@probonopd  I am closing this as well. This doesn't seem to be maintained anymore. The install script still fails on Debian and Python versions is stuck at 3.5. In addition it is actually quite easy to extract the latest Python runtimes from the manylinux Docker images as done in the new [python-appimage](https://github.com/niess/python-appimage) project.

**Comment by probonopd** [comment]
That is seriously cool. Did you consider to upstream those manylinux Python builds to the Python project?

**Comment by niess** [comment]
@probonopd I just notified people from the manylinux project, right now. This might be of interest to them indeed and since I am using their builds it seems fair.

I am not really in touch with the Python community. There seem to be a large bunch of tools to interact with them (forums, slack, IRC, ...). I am somehow lost. It must mean that I am too old school now :P I'll have a look tonight.
