### ISSUE TITLE
Rewrite the plugin in Python?

### ISSUE THREAD

**Issue by niess** [niess/linuxdeploy-plugin-python#18]
It would be cool (and easier to update/maintain) if the plugin was actually written in Python.  It would be even more cool if it was written using Python 3 latest stable release, e.g. with some bootstrap procedure for generating the plugin AppImage.

**Comment by niess** [comment]
@anki-code @probonopd I did some progress on this issue (feature :P) over the last days. However it was easier to start things from scratch using the experience acquired with the linuxdeploy-plugin-python project. So I set up a new repo over there: [python-appimage](https://github.com/niess/python-appimage). The doc is missing for now. I explain the motivations below.

As you can see this is no more a plugin for linuxdeploy but actually a pure Python 2/3 package [available over PyPI](https://pypi.org/project/python-appimage/). The package has no explicit deps out of vanilla Python. Currently it downloads patchelf & appimagetool from the web.

The scope has been simplified. It simply relocates an **existing** python installation to an AppImage. By default it will relocate the Python used to run the package. But a specific Python can be provided as well. The relocation is done as in linuxdeploy-plugin-python, using the same tricks.

A special mode allows to extract & package the Pythons installed in the manylinux Docker images. I recently realised that these Docker images actually already have various Pythons installed & optimised (from 2.7 to 3.8). This provides smaller Pythons AppImages with full PEP binary compatibility. Also compared to linuxdeploy-plugin-python it is blazing fast now to "build" a Python AppImage.

Concerning extra packages, i.e. pip installed ones, I changed paradigm. I am assuming that they (will) properly ship their binary dependencies. This is true for many Python packages now days providing proper wheels compatible with (built on) manylinux. If not, there is a specific tool still under development: [auditwheel](https://github.com/pypa/auditwheel) that allows to fix (repair) the binary deps of Python wheels. I feel like it makes more sense to follow this standardisation effort of the Python community rather than tinkering my own solutions for "broken" packages & doubling the work.

At then end, the [python-appimage](https://github.com/niess/python-appimage) package is actually not needed anymore in order to build a Python app. One can just pull a suitable AppImage of vanilla Python from the [releases area](https://github.com/niess/python-appimage/releases), extract and pip install to it. Then repack it using your favourite tool :P I find It more convenient and flexible that way - rather than having one script that rules them all.

_P.S. The new manylinux Python AppImages are built using GitHub workflow no more Travis. I found it more convenient (though there is still room for improvement) and furthermore one gets more simultaneous jobs. This also speeds up the whole build procedure._

**Comment by anki-code** [comment]
Could you please create an example for xonsh or xxh? 😃

**Comment by niess** [comment]
@anki-code I added a mode for building "simple" applications from a folder containing some meta-data. For example for Xonsh the command is:

```sh
python -m python_appimage build app applications/xonsh
```
The Xonsh application meta data are [over there](https://github.com/niess/python-appimage/tree/master/applications/xonsh).

I didn't document it yet. The command line option `-h` gives some indications, e.g:

```sh
python -m python_appimage build app -h
```
(or `python-appimage build app -h` if you installed the package entry point.)

**Comment by anki-code** [comment]
I tried:
```
mkdir ~/pyai && cd ~/pyai
git clone https://github.com/niess/python-appimage
cd python-appimage
python -m python_appimage build app applications/xonsh

[2020-04-04 11:43:42,114] EXTRACT  python3.8.2-cp38-cp38-manylinux1_x86_64.AppImage
[2020-04-04 11:43:47,094] BUNDLE   xonsh.desktop
[2020-04-04 11:43:47,095] BUNDLE   xonsh.appdata.xml
[2020-04-04 11:43:48,614] BUNDLE   xonsh
[2020-04-04 11:43:49,946] BUNDLE   prompt_toolkit
[2020-04-04 11:43:50,922] BUNDLE   Pygments
[2020-04-04 11:43:51,981] BUNDLE   entrypoint.sh
[2020-04-04 11:43:51,981] BUILD    AppDir
appimagetool, continuous build (commit 7392c48), build 2120 built on 2020-03-10 18:42:43 UTC
Using architecture x86_64
AppStream upstream metadata found in usr/share/metainfo/xonsh.appdata.xml
/tmp/python-appimage-hdy5yajl/AppDir should be packaged as xonsh-x86_64.AppImage
Trying to validate AppStream information with the appstreamcli tool
In case of issues, please refer to https://github.com/ximion/appstream
xonsh.appdata.xml
  W: xonsh:3: cid-desktopapp-is-not-rdns xonsh
  E: xonsh:4: metadata-license-invalid
  E: xonsh:7: summary-has-tabs-or-linebreaks
  I: xonsh:10: description-first-para-too-short   Python 3.8.2 + Xonsh bundled in an AppImage.
        
  I: xonsh:14: url-not-secure http://xon.sh

Validation failed: errors: 2, warnings: 1, infos: 2
Failed to validate AppStream information with appstreamcli

Traceback (most recent call last):
  File "/home/pc/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pc/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pc/xxh/pa/python-appimage/python_appimage/__main__.py", line 92, in <module>
    main()
  File "/home/pc/xxh/pa/python-appimage/python_appimage/__main__.py", line 88, in main
    command.execute(*command._unpack_args(args))
  File "/home/pc/xxh/pa/python-appimage/python_appimage/commands/build/app.py", line 239, in execute
    build_appimage(destination=destination)
  File "/home/pc/xxh/pa/python-appimage/python_appimage/appimage/build.py", line 52, in build_appimage
    raise RuntimeError('Could not build AppImage')
RuntimeError: Could not build AppImage
```
What I'm doing wrong? Thanks!

**Comment by niess** [comment]
@anki-code Nothing wrong on your side :) `appstreamcli` tool is reporting errors in the provided appdata.xml file. Errors are reported on stderr which stops the python-appimage build. I don't have `appstreamcli` installed so I never tested this case. I will have to filter stderr for `appstreamcli` messages. I am already doing it for some other cases.

If you could temporarily disable `appstreamcli` it shoudl work.

**Comment by anki-code** [comment]
1. I renamed `/usr/bin/appstreamcli` and it works!

2. I've fixed a small issue - https://github.com/niess/python-appimage/pull/1

3. It will be cool if there will be an python symlink in the AppImage which will not be related to python version. For example `usr/bin/python`. For now there is `python***` execute file for every version.

Thanks!

**Comment by niess** [comment]
@anki-code Thank you for the patch.

I added generic `python` and `pythonX` symlinks to the new Python AppImages.

Still need to catch apstreamcli messages.

**Comment by niess** [comment]
@anki-code Finally I disabled apstream checks when building the AppImage because it doesn't seem to be stable right now (see e.g. [this issue](https://github.com/AppImage/AppImageKit/issues/603)). For example the version that I get on Debian 9 reports errors for things that have actually been updated :( preventing the build to success.

If you want to validate your appstream data you can still run `appstreamcli` manually though.

So we the lastest realease you should be able to build the images without disabling your `appstreamcli`.

**Comment by anki-code** [comment]
Good, it works!

I've faced with this two things:
1. Unusable shebang in extracted mode.:
```
xonsh-x86_64.AppImage --appimage-extract
$ head -n1 squashfs-root/opt/python3.8/bin/xonsh
#!/tmp/python-appimage-zi6w9_vp/AppDir/usr/bin/../../opt/python3.8/bin/python3.8
```
This not allows to extract appimage and use xonsh. The old appimage has relative shebang:
```
#!/bin/sh
"exec" "$(dirname $(readlink -f ${0}))/../../bin/python3.8" "$0" "$@"
from xonsh.main import main
main()
```

2. The xonsh start script is under python directory with version number (`python3.8/bin/xonsh`). This not allow to set generic path to xonsh for any version. But I not need for this now. It's just for info.

**Comment by niess** [comment]
@anki-code I added a shebang patcher to the `sitecustomize.py` that is triggered at exit wenever `pip` was loaded and `install` was invoked from the CLI. It sets relative shebangs using the same trick than for linuxdeploy-plugin-python.

Concerning your second issue, indeed the pip installed scripts are not mirrored to `usr/bin`. It might not always be desirable to do so. Therefore I decided to leave it up to the application builder to do it himself. For example you could add a post process where you extract the AppImage, add some symlinks, extra hooks etc., and then rebuild the AppImage.

**Comment by anki-code** [comment]
It works like a charm! Many thanks!

**Comment by niess** [comment]
@anki-code Finally I added a hook for exporting pip installed scripts to usr/bin. In order to ease working with an extracted AppImage. But I am not 100% happy with this. It does have some issues. For example only python scripts are forwarded, not bash one (xon.sh namely).

Also I added a hook for `pip uninstall` in order to clean broken links following an uninstall.

Actually it would would be much easier if python was installed to `usr/`. That would solve much issues. But that's not ideal from the point of view of the AppImage spec where the image might contain multiple software.  As an alternative I could simply add a symlink the like `opt/python` pointing to the latest Python version. That way one simply needs to export `opt/python/bin` to the `PATH` in order to work from the extracted image.

I'll have to think a bit more about this. Anyway, things might change in the following days :P

**Comment by niess** [comment]
@anki-code I stuck to the initial plan: mirroring scripts from opt/python*/bin to usr/bin. But I improved the `atexit` algorithm in order to sync all new scripts under bin, presumably installed by pip. There might be some tricky cases where this fails. But let's see ...

I am happy now with the new tool. It satisfies my needs. I understood that it is doing the job as well on your side. So I am closing this issue. If you have some new issues related with this please report them on the new project page directly :) Thank you!
