### ISSUE TITLE
bin/xonsh double check

### ISSUE THREAD

**Issue by anki-code** [niess/linuxdeploy-plugin-python#21]
Hey @niess! Thank you for your great work here!

I just want to double check. After extracting `xonsh.AppImage` I see in `squashfs/usr/python/bin/xonsh` the file [after sanitizing](https://github.com/niess/linuxdeploy-plugin-python/blob/master/linuxdeploy-plugin-python.sh#L166):
```
#!/bin/sh
"exec" "$(dirname $(readlink -f ${0}))/../../bin/python3.8" "$0" "$@"

from xonsh.main import main
main()
```

Is that correct? I don't clearly understand why sh and python were  mixed )
Feel free to close this issue.

**Comment by niess** [comment]
Hello @anki-code,

this looks ugly indeed but it allows to mimic a shebang relative to the file. Ideally I would have done something like:

```python
#! $(dirname __file__)/relative/path/to/the/appimage/python3.8

from xonsh.main import main
main()
```
But that's not a valid shebang. The previous trick does the job. Yet the file is first interpreted as an sh file. I came across this by googling. But, maybe there are more elegant and/or obvious solutions for this case?

**Comment by anki-code** [comment]
Got it! It works :)

**Comment by niess** [comment]
An alternative could be to add $APPDIR/python/bin at the head of the PATH in the AppRun script. Then one could use `#! /usr/bin/env python3.8` as shebang. But I was not so happy with the wrapper modifying the PATH which could have unexpected side effects. The present solution looks ugly but it closely mimics a classic python install.
