### ISSUE TITLE
Reduce appimage size

### ISSUE THREAD

**Issue by anki-code** [niess/linuxdeploy-plugin-python#26]
Hi! Thanks for your work!

Is there a way to reduce appimage size? 
While I review python lib files in app image I see test files, licences, h-files.
Probably there is a clening tool to remove all of this files?

Thanks!

**Comment by probonopd** [comment]
With some manual work it is possible, yes. Please see https://github.com/niess/linuxdeploy-plugin-python/issues/1 for one way to do it.

**Comment by anki-code** [comment]
Oh, my bad! Thanks!

**Comment by niess** [comment]
@anki-code: by default the produced AppImage contains a full Python environment. That's OK for my use case which is to provide a fully featured yet portable python. But for specific apps some additional cleanup could be done indeed. This needs to be done manually for now :(
