### ISSUE TITLE
How to use the AppImage from here to build a venv using pip?

### ISSUE THREAD

**Issue by probonopd** [niess/linuxdeploy-plugin-python#27]
I am trying to make an AppDir that conatins a portable version of Python and some software installed by pip3. The following works for me:

```
sudo apt install python3-pip python3-venv libxkbcommon-x11-0 # Needed by PyQt5 from pip

mkdir ./appdir
sudo mount -t tmpfs tmpfs ./appdir/ -o strictatime 

wget -c https://downloads.egenix.com/python/install-pyrun
bash install-pyrun --python=3.5 ./appdir/usr/

./appdir/usr/bin/pip3 install PyQt5 pyserial

mkdir -p ./appdir/usr/share/
( cd ./appdir/usr/share/ ; git clone https://github.com/tasmota/tasmotizer )

./appdir/usr/bin/python3 ./appdir/usr/share/tasmotizer/tasmotizer.py
```

Note that I did not need to compile Qt. The precompiled one from PyPi was used.

Instead of using `pyrun` (a portable Python distribution) I would like to use python3.8.1-x86_64.AppImage. Is there a way to do this?

How can the same be achieved with https://github.com/niess/linuxdeploy-plugin-python/releases/download/continuous/python3.8.1-x86_64.AppImage?

**Comment by niess** [comment]
@probonopd, the following works for me on Debian 9:

```bash
#! /bin/bash

# Get and extract the Python AppImage
curl -L -s -o python3.8.1-x86_64.AppImage https://github.com/niess/linuxdeploy-plugin-python/releases/download/continuous/pyth
on3.8.1-x86_64.AppImage
chmod u+x python3.8.1-x86_64.AppImage
./python3.8.1-x86_64.AppImage --appimage-extract > /dev/null
mv squashfs-root AppDir

# Configure the environment as if running from the AppImage
export APPDIR=$PWD/AppDir
python="${APPDIR}/AppRun"

# Get the fancy package from GitHub
( cd AppDir/usr/share/ ; git clone https://github.com/tasmota/tasmotizer )

# Install dependecies to the image using pip. Note that we first need to update
# pip otherwise PyQt5 fails to install
$python -m pip install -U pip
$python -m pip install -r AppDir/usr/share/tasmotizer/requirements.txt

# Run the fancy script
$python AppDir/usr/share/tasmotizer/tasmotizer.py
```
This is close to your example. However pushing further this exercise I have two issues.
1. The pip install of PyQt5 fails when using a manylinux image. Generally speaking the pip install of PyQt5 seems to be not so reliable. E.g. I had to update pip before getting it to work. Googling the issues that I had some people seem to recommend using a source install of PyQt5 with sip instead of using pip. I didn't try this.

2. Despite pip installed a binary distribution of PyQt5 (wheel), the re-packaged AppImage does not work when moved to another system, e.g. CentOS 7. It fails due to missing dependencies (xcb) not packaged by PyQt5's wheel (?)

**Comment by niess** [comment]
By the way, there is no need to install pip or venv in this case. Those are contained in the Python AppImage. In addition, I already had libxkbcommon-x11-0 installed on both the Debian 9 and CentOS 7 that I tried, maybe due to previous installs of Qt?

**Comment by niess** [comment]
Also, PyQt5 is installed in `AppDir/usr/python/lib/python3.8/site-packages/PyQt5`. One could check the dependencies of the Python packages there (.so files) using ldd. Qt5 libraries are under `PyQt5/Qt/lib`. Again one could check and package the corresponding dependencies. The linuxdeploy-plugin-python script does this job. However, it does not currently support running from an existing AppImage, only from a source distribution of Python.

**Comment by niess** [comment]
@probonopd : After some debugging I finally realized that the CentOS 7 that I was using actually does not have `libxkbcommon-x11` but only `libxkbcommon` which was preventing the AppImage to run. I copied  libxkbcommon-x11 (Debian 9) to `PyQt5/Qt/lib` (the Qt libs there use RPATH=$ORIGIN) and now the image works on Cent OS 7  as well. I created a temporary release with the [tasmotize imager](https://github.com/niess/linuxdeploy-plugin-python/releases/download/test/tasmotizer-x86_64.AppImage) as asset if you like to try it?

**Comment by probonopd** [comment]
Thank you very much. I didn't think of extracting the AppImage, I was looking for some sort of venv command, but this of course does the trick. :+1

Strangely, the Tasmotize AppImage does not work anymore as soon as it is extracted to an AppDir. Do you know why?

```
me@host:~$  '/home/me/Downloads/tasmotizer-x86_64.AppImage' --appimage-extract 
me@host:~$ ./squashfs-root/AppRun 
ls: cannot access '/home/me/squashfs-root/../../usr/python/share/tcltk/tcl*': No such file or directory
ls: cannot access '/home/me/squashfs-root/../../usr/python/share/tcltk/tk*': No such file or directory
./squashfs-root/AppRun: line 41: /home/me/squashfs-root/../../usr/python/bin/python3.8: No such file or directory
```

**Comment by niess** [comment]
@probonopd There was a bug with the AppRun. I wrongly assumed that it was a symbolic link to the Python executable inside the image. Instead it was a copy, resulting in these strange errors. It should be fixed now. I updated the [tasmotizer image](https://github.com/niess/linuxdeploy-plugin-python/releases/download/test/tasmotizer-x86_64.AppImage).

@anki-code I cleaned the AppRun & entrypoint feature. Previously the entry point was located directly into the Python wrapper resulting in a modified `python` executable. Now the entrypoint is located in the AppRun. Basically the AppRun just call the image Python, with some entry point options. This should it make easier for people to extract & modify the image. One just needs to pip install and then to edit the AppRun. Please let me know if this new behaviour is problematic for your Xonsh image? I did some basic tests on my side and it seems to be OK.

**Comment by anki-code** [comment]
@niess First of all I want to let you know that I forked this repo to xxh/linuxdeploy-plugin-python and did continuous build of `xonsh.AppImage`. Thank you very much for travis configs!

This means the xxh has no direct dependency on your repo and you free for experiments.

> Please let me know if this new behaviour is problematic for your Xonsh image? 

I've tested the new image and it affects on xxh entrypoint in extracted mode. I should fix it for xxh and as I wrtote above you did not break the xxh so don't worry.

**Comment by niess** [comment]
@anki-code Fine :)

I was wondering: do you still need the Xonsh AppImage to be generated here? I mean, that it might be a bit confusing for people to have two projects providing different xonsh AppImages. I could link to your Xonsh AppImages in this README?

Let me know :)

**Comment by anki-code** [comment]
I think it will be super cool if you continue support xonsh version:
1. The python shell is a bit different and good for tests I think
2. I'm not so experienced in building AppImages and my repo is just a freezed state of your work. It will be great if plugin-python will grow and I have ability to pull great things :)
Thank you for your work!

**Comment by probonopd** [comment]
> It should be fixed now. I updated the tasmotizer image.

Thank you very much @niess. 
I think this would be useful to leave in your repository as a real-life example how to package a somewhat more complex GUI app with your tools.

Just one minor nitpick:

```
me@host:~$ '/home/me/Downloads/tasmotizer-x86_64.AppImage'
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/tmp/.mount_tasmotJDOmc1/usr/bin/python3.8: line 41:  9278 Aborted                 ( PYTHONHOME="${APPDIR}/
```

Bundling  libxkbcommon-x11-0 inside the AppImage would easily fix this.

**Comment by niess** [comment]
@probonopd I actually packaged libxkbcommon-x11 under `usr/python/lib/python3.8/site-packages/PyQt5/Qt/lib`. But apparently not properly. I will close this issue for now. The new [python-appimage](https://github.com/niess/python-appimage) package allows to build such apps more easily. See for example `applications/tasmotizer`. Yet, it doesn't package the missing `libxkbcommon-x11-0`. But shouldn't it be in the PyQt5 Python wheel actually? To me it looks more like a mistake on their side.
