### ISSUE TITLE
PIP_REQUIREMENTS='boto3==1.11.3' break with sed error

### ISSUE THREAD

**Issue by raymondsamalo** [niess/linuxdeploy-plugin-python#29]
boto3 includes s3transfer, somehow when building with the latest release the build script show sed error where sed trying to modify __pycache__ folder and end up with exit errocode 4 

This issue does not appear in build f227220f885428f62012f4239f9ba7bca495dec6

[python/stderr] sed: couldn't edit __pycache__: not a regular file
ERROR: Failed to run plugin: python (exit code: 4)

**Comment by niess** [comment]
@raymondsamalo I fixed [this line](https://github.com/niess/linuxdeploy-plugin-python/blob/master/linuxdeploy-plugin-python.sh#L191). A directory has exec permission. Hence it was wrongly considered as an executable. At install boto3, or one of its deps, generates a __pycache__ folder inside the bin folder.

I updated the plugin AppImage as well. Let me know if this fixes your issue, or not?

**Comment by raymondsamalo** [comment]
thanks @niess the fix fixed the issue
really grateful for the super fast response to fix this

**Comment by niess** [comment]
@raymondsamalo Great. Thank your for reporting this bug :)
