### ISSUE TITLE
ls: cannot access 'python?.?': No such file or directory

### ISSUE THREAD

**Issue by JulianChia** [niess/linuxdeploy-plugin-python#32]
After issuing this command, `./appimagetool-x86_64.AppImage  APPDIR/` and after the compiled Python was installed,  this msg appeared.

This msg seems to be caused by https://github.com/niess/linuxdeploy-plugin-python/blob/18d846128da7d95081a203f5511c72ee1b73502e/linuxdeploy-plugin-python.sh#L172

As such, the rest of the script could not be done.

**Comment by niess** [comment]
Hello @JulianChia,

my apologies, but this project is no more maintained. You might use [python-appimage](https://github.com/niess/python-appimage) instead, if it suits your needs.
