### ISSUE TITLE
Allow to extend an existing Python AppImage

### ISSUE THREAD

**Issue by niess** [niess/linuxdeploy-plugin-python#8]
If the Python source is an existing AppImage, extract it and copy the relevant objects to AppDir. This would allow to extend a base Python AppImage and simplify / speed up the build process.

**Comment by alfem** [comment]
I tried to mount one of the released python appimage, copy the content to a new Appdir and install some modules with pip, but no luck. 
In a second attempt, I used the python appimage to run a '-m pip install --user my-required-modules'. Then copied these installed modules from my user diretory to the appdir and then generated a new appimage. It seem to work, but I got a weird (unrelated to the new modules) error with TK.

Now I am triying to generate my own python appimage from sources, and again bump into TK issues.

**Comment by anki-code** [comment]
@alfem maybe you could help right paths. What I'm doing for fix it in `xonsh.AppImage`:

```
$ ./xonsh.AppImage
xonsh# python
ImportError: No module named site 

xonsh# $PYTHONHOME
'/tmp/.mount_xonsh-*****/usr/python'

xonsh# $PATH=[ $PYTHONHOME + '/bin' ] + $PATH
xonsh# python
Python 3.7.3
>>> #success

xonsh# $PIP_TARGET='/tmp/xonsh/pip'
xonsh# import sys
xonsh# sys.path.append('/tmp/xonsh/pip') 

xonsh# pip3 install tqdm
xonsh# python
Python 3.7.3
>>> import tqdm
>>> # success
```

**Comment by niess** [comment]
Hello @alfem. Building from an existing Python image is not yet implemented. That was just an idea so far.

Concerning your Tk issue that's strange. In principle the linuxdeploy-plugin-python script should handle it, see [here](https://github.com/niess/linuxdeploy-plugin-python/blob/master/linuxdeploy-plugin-python.sh#L248). One issue is that Tk requires some data to be copied to the appimage, usually found under /usr/share/. But the exact location depends on the OS. The script was tested only on Debian and CentOS.

How do you build your image? I'm building with Docker in two steps, as in the [.travis.yml](https://github.com/niess/linuxdeploy-plugin-python/blob/master/.travis.yml). First a build a Docker image with the required dependencies. Then I use it (run) to build the AppImages. Note that you could simply pull my image from Dcokerhub as well.

**Comment by niess** [comment]
@alfem: The build script that I use is actually in the [appimage](https://github.com/niess/linuxdeploy-plugin-python/tree/master/appimage) folder. It uses recipes from the corresponding [folder](https://github.com/niess/linuxdeploy-plugin-python/tree/master/appimage/recipes). Maybe the easiest would be to write your own recipe and use the build script? For example, from the root of the repo:
```
appimage/build-python xonsh
```
builds the xonsh image from the corresponding recipe ([xonsh.sh](https://github.com/niess/linuxdeploy-plugin-python/blob/master/appimage/recipes/xonsh.sh)).

I'm doing this through Docker in order to get a portable AppImage. The [manylinux](https://www.python.org/dev/peps/pep-0571/) image is used that for. But as a 1st trial you could do it on your host. Just create your own recipe is the corresponding folder.

**Comment by alfem** [comment]
It was my fault! Finally It worked following these steps:

1) Download the 3.7.5 appimage, and use it to install the requirements (pycos, websocket-client and six) with pip in my home directory:  _python3.7.5-x86_64.AppImage -m pip install --user pycos, websocket-client, six_
2) Mount the appimage and copy the full content to a new AppDir folder
3) Copy the installed modules from my home directory to the new AppDir, inside _AppDir/usr/python/lib/python3.7/site-packages_ 
4) Generate the new appimage with appimagetool

**Comment by niess** [comment]
Great that it worked out :) It might not always be that simple if the Python packages are not relocatable though. Or if they depend on external/system shared libraries. But I like your solution since it mostly implies standard shell commands.

According to @anki-code answer you could also specify the install location of `pip` by exporting PIP_TARGET. SO for example:

```
export PIP_TARGET=/path/to/AppDir/usr/python/lib/python3.7/site-packages
./python3.7.5-x86_64.AppImage -m pip install --user pycos, websocket-client, six
```
So you don't spoil your home.
